##server:
##  servlet:
##    context-path: /myapp
#
#logging:
#  level:
#    org:
#      springframework: ERROR
#
#spring:
#  main:
#    banner-mode: console
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  batch:
#    job:
#      enabled: false
#  jpa:
#      hibernate.ddl-auto: update
#      generate-ddl: false
#      show-sql: false
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.H2Dialect
#      database-platform: org.hibernate.dialect.H2Dialect